networks:
  grafana_network:

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    networks:
      - grafana_network

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      restart: unless-stopped
      ports:
        - "9090:9090"
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/var/prometheus'
        - '--storage.tsdb.retention.time=10y'
        - '--web.enable-remote-write-receiver'
      volumes:
        - ./prometheus/config:/etc/prometheus
        - ./prometheus/data:/var/prometheus
      networks:
        - grafana_network

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki/config:/etc/loki
      - ./loki/data:/var/loki
    networks:
      - grafana_network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    restart: unless-stopped
    ports:
      - "3200:3200"   # HTTP API
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    command:
      - -config.file=/etc/tempo/tempo.yml
    volumes:
      - ./tempo/config:/etc/tempo
      - ./tempo/data:/var/tempo
    networks:
      - grafana_network

