name: Test Coverage Validation

on:
  pull_request:
    types:
      [ opened, synchronize, reopened ]

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository íŒŒì¼ ë¶ˆëŸ¬ì˜¤ê¸°
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: JDK ë²„ì „ 21 ì„¤ì¹˜
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 21

      - name: Gradle Wrapper ì‹¤í–‰ ê¶Œí•œ ë¶€ì—¬
        run: chmod +x ./gradlew

      - name: ì „ì²´ ë¹Œë“œ ë° í…ŒìŠ¤íŠ¸
        run: ./gradlew --info test

      - name: JaCoCo ì»¤ë²„ë¦¬ì§€ ë¦¬í¬íŠ¸ ìƒì„±
        id: jacoco_report
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 70
          min-coverage-changed-files: 70
          title: "ğŸ§ª í…ŒìŠ¤íŠ¸ ì»¤ë²„ë¦¬ì§€ ë¦¬í¬íŠ¸"
          update-comment: true

      - name: Close PR, if build fail
        if: ${{ failure() }}
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_number = ${{ github.event.pull_request.number }}
            const updated_title = `[VALIDATION FAIL] ${{ github.event.pull_request.title }}`
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              body: 'ë¹Œë“œ ë˜ëŠ” í…ŒìŠ¤íŠ¸ ì»¤ë²„ë¦¬ì§€ ê²€ì¦ì— ì‹¤íŒ¨í–ˆìŠµë‹ˆë‹¤.',
              event: 'REQUEST_CHANGES'
            })
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              title: updated_title,
              state: 'closed'
            })
